### ISSUE TITLE
Modulo de dmri-explorer

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#23]
Había hecho un modulo para [dmri-explorer](https://github.com/scilus/dmri-explorer),  El software esta en `lanirem-softwrae/dmri-explorer`

Quedó en la beta de modulos por que si no mal reucerdo no pude hacer jalar el binario. Al final no supe por que. 

Valdrá la pena revisar pro que no funcionaba o ya mejor borramos la carpeta?

**Comment by lconcha** [comment]
Sí funciona el binario que tienes en esa carpeta. Lo que pasa es que `dmriexplorer` no abre si no le das al menos una imagen para abrir desde la terminal. Entonces el módulo es bueno y debe pasar fuera de beta.

**Comment by lconcha** [comment]
Cerrar después de hacer módulo.

**Comment by RicardoRios46** [comment]
Resuelto en #27
