### ISSUE TITLE
modulo de deeplabcut

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#24]
Habia hecho un modulo para deeplabcut que cargaba un ambiente de conda/mamba con la libreria instalada.

Al final no tuve chance de probarlo ni nadie me ayudo a calarlo en la beta. No se si funciona pero para que jale adecuadamente solo vale la pena para las compus con GPU.

Valdra la pena dejar el modulo o lo borramos?

**Comment by lconcha** [comment]
parece que la (poca) gente que usa deeplabcut sabe lo que hace y se hacen sus propios envs. Creo que podemos borrarlo.
