### ISSUE TITLE
eliminar alias de fmrilab_configfile

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#25]
Habían creado unas funciones en  `fmrilab_configfile`,  que imitaban el comportamiento de los antiguos alias para cargar software en el cluster (mrtrix3, fsl6 y freesurfer7).

Estas funciones en realidad ya cargan los modulos.

Sera que ya las borramos ya para que todos adopten lo de los modulos? 

Esperaria que nadie las siga usando.

**Comment by lconcha** [comment]
Ya llevamos un rato con los módulos y funcionan bien. Las pocas personas que tengan el error se comunicarán con nosotros y les diremos que usen módulos. Borremos las funciones entonces.
