### ISSUE TITLE
soporte no peude ejecutar los scripts adicionales para x2go desde cualquier lado

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#26]
Habia creado dos scrips (x2go_end_IDLEsessions.sh y x2go_list_IDLEsessions) para enlistar o eliminar las sesiones abiertas de x2go que estuvieran abiertas mucho tiempo (por default 7 dias).

Los scripts funcionan adecuadamente si los ejecutas directamente. Pero a pesar de que el perfil de soporte anade a su path las admin_tools en su bashrc, no los puedes ejecutar en una seion nueva. 

Me falto algo para que los pueda ver/ejecutar directamente desde cualquier lado en la terminal?

**Comment by lconcha** [comment]
sí los corre, pero solo con el path absoluto. No es bug, es feature, porque andar matando sesiones es gran responsabilidad y esto me hace poner atención.
