### ISSUE TITLE
brkraw

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#28]
Este canijo!

Voy a borrar dos ambientes de micromamba que se quedaron en la beta de los modulos:
- 0.3.10  que segun yo hace lo mismo que el que tenemos ahorita de 0.3.11
- 0.3.07  es uno que me la pase un dia re armandolo para que os garzos pudieran probar si servia el bids converter pero nunca lo pelaron.

Veo que en la pagina del brkraw anuncian que se viene un gran[update](https://github.com/BrkRaw/brkraw/issues/146)

Con suerte eso resuelve los problemas que anda arrastrando brkraw desde hace rato.

Lo malo es que segun era para febrero y ya es marzo. Asi que quien sabe que tan realista sea, pero le podemos echar el ojo.

**Comment by lconcha** [comment]
Esperamos ansiosos los updates del brkraw.
