### ISSUE TITLE
fsl/6.0.5.2

### ISSUE THREAD

**Issue by RicardoRios46** [lconcha/admin_tools#29]
Habia creado este modulo con la intencion de tener una instalacion fucional de fslview. El fslview funciona pero el resto del fsl del modulo tiene probelmas.

Este modulo fue creado con el instalador legacy de fsl, el cual en toeria tienen para instalar versiones viejas de fsl. En la practica no funciona muy bien, ya que se hace bolas con el python viejo en la instalacion y la deja a medias.

todavía habrá banda usando fslview?

**Comment by lconcha** [comment]
Yo creo que es momento de olvidarnos de fslview. Tenemos muchos otros visores rápidos como mrview, afni, etc. Para quien quiera ver cosas de Feat y así, pues que use fsleyes.
